// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IOrderRoute is an autogenerated mock type for the IOrderRoute type
type IOrderRoute struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *IOrderRoute) Run() {
	_m.Called()
}

type mockConstructorTestingTNewIOrderRoute interface {
	mock.TestingT
	Cleanup(func())
}

// NewIOrderRoute creates a new instance of IOrderRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIOrderRoute(t mockConstructorTestingTNewIOrderRoute) *IOrderRoute {
	mock := &IOrderRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
