// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	clients "order-service/clients/invoice"

	mock "github.com/stretchr/testify/mock"
)

// IInvoiceClient is an autogenerated mock type for the IInvoiceClient type
type IInvoiceClient struct {
	mock.Mock
}

// GenerateInvoice provides a mock function with given fields: _a0, _a1
func (_m *IInvoiceClient) GenerateInvoice(_a0 context.Context, _a1 *clients.InvoiceRequest) (*clients.InvoiceData, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *clients.InvoiceData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *clients.InvoiceRequest) (*clients.InvoiceData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *clients.InvoiceRequest) *clients.InvoiceData); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clients.InvoiceData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *clients.InvoiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIInvoiceClient creates a new instance of IInvoiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInvoiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInvoiceClient {
	mock := &IInvoiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
