# golangci-lint configuration
run:
  # Timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
  # Include test files or not, default is true
  tests: false
  # Skip test files and protobuf generated code
  modules-download-mode: readonly
  # Allow multiple parallel golangci-lint instances running
  allow-parallel-runners: true

# Output configuration options
output:
  # Replacing deprecated format option with formats
  formats: [code-climate]

# Linters configuration settings
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    default-signifies-exhaustive: true

  gocognit:
    min-complexity: 30

  gocyclo:
    min-complexity: 30

  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx

# Enable/disable linters
linters:
  disable-all: true
  enable:
    # Recommended level 0 linters
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gosec
    - govet
    - staticcheck
    - typecheck

    # Level 1 linters
    - cyclop
    - durationcheck
    - forcetypeassert
    - gocognit
    - gocyclo
    - ineffassign
    - makezero
    - prealloc
    - unconvert
    - unused

    # Level 2 linters
    - dogsled
    - dupl
    - forbidigo
    - gosimple
    - gochecknoinits
    - goconst
    - gocritic
    - godox
    - revive
    - err113
    - stylecheck

    # Level 3 linters
    - gofmt
    - goimports
    - importas
    - lll
    - nakedret
    - nolintlint
    - paralleltest
    - thelper

# Issues exclusion rules
issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.pb\\.gw\\.go$"

  # Excluding specific rules
  exclude-rules:
    - linters:
        - gocritic
      text: "unnecessaryDefer:"