// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	models "order-service/domain/models"
)

// IOrderInvoiceRepository is an autogenerated mock type for the IOrderInvoiceRepository type
type IOrderInvoiceRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *IOrderInvoiceRepository) Create(_a0 context.Context, _a1 *gorm.DB, _a2 *models.OrderInvoice) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *models.OrderInvoice) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOrderInvoiceRepository creates a new instance of IOrderInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderInvoiceRepository {
	mock := &IOrderInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
