// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	order "order-service/controllers/order"

	mock "github.com/stretchr/testify/mock"
)

// IControllerRegistry is an autogenerated mock type for the IControllerRegistry type
type IControllerRegistry struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields:
func (_m *IControllerRegistry) GetOrder() order.IOrderController {
	ret := _m.Called()

	var r0 order.IOrderController
	if rf, ok := ret.Get(0).(func() order.IOrderController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order.IOrderController)
		}
	}

	return r0
}

type mockConstructorTestingTNewIControllerRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewIControllerRegistry creates a new instance of IControllerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIControllerRegistry(t mockConstructorTestingTNewIControllerRegistry) *IControllerRegistry {
	mock := &IControllerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
