// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	clients "order-service/clients/invoice"

	mock "github.com/stretchr/testify/mock"

	payment "order-service/clients/payment"
)

// IClientRegistry is an autogenerated mock type for the IClientRegistry type
type IClientRegistry struct {
	mock.Mock
}

// GetInvoice provides a mock function with given fields:
func (_m *IClientRegistry) GetInvoice() clients.IInvoiceClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInvoice")
	}

	var r0 clients.IInvoiceClient
	if rf, ok := ret.Get(0).(func() clients.IInvoiceClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clients.IInvoiceClient)
		}
	}

	return r0
}

// GetPayment provides a mock function with given fields:
func (_m *IClientRegistry) GetPayment() payment.IPaymentClient {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPayment")
	}

	var r0 payment.IPaymentClient
	if rf, ok := ret.Get(0).(func() payment.IPaymentClient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(payment.IPaymentClient)
		}
	}

	return r0
}

// NewIClientRegistry creates a new instance of IClientRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClientRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClientRegistry {
	mock := &IClientRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
