// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	services "order-service/services/suborder"
)

// IServiceRegistry is an autogenerated mock type for the IServiceRegistry type
type IServiceRegistry struct {
	mock.Mock
}

// GetSubOrder provides a mock function with given fields:
func (_m *IServiceRegistry) GetSubOrder() services.ISubOrderService {
	ret := _m.Called()

	var r0 services.ISubOrderService
	if rf, ok := ret.Get(0).(func() services.ISubOrderService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.ISubOrderService)
		}
	}

	return r0
}

// NewIServiceRegistry creates a new instance of IServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIServiceRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IServiceRegistry {
	mock := &IServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
