// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	order "order-service/services/order"

	mock "github.com/stretchr/testify/mock"
)

// IServiceRegistry is an autogenerated mock type for the IServiceRegistry type
type IServiceRegistry struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields:
func (_m *IServiceRegistry) GetOrder() order.IOrderService {
	ret := _m.Called()

	var r0 order.IOrderService
	if rf, ok := ret.Get(0).(func() order.IOrderService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order.IOrderService)
		}
	}

	return r0
}

type mockConstructorTestingTNewIServiceRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// NewIServiceRegistry creates a new instance of IServiceRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIServiceRegistry(t mockConstructorTestingTNewIServiceRegistry) *IServiceRegistry {
	mock := &IServiceRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
