// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	circuitbreaker "order-service/common/circuitbreaker"

	mock "github.com/stretchr/testify/mock"
)

// ICircuitBreaker is an autogenerated mock type for the ICircuitBreaker type
type ICircuitBreaker struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ICircuitBreaker) Execute(_a0 context.Context, _a1 circuitbreaker.BreakerFunc) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, circuitbreaker.BreakerFunc) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICircuitBreaker creates a new instance of ICircuitBreaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICircuitBreaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICircuitBreaker {
	mock := &ICircuitBreaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
