// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IOrderController is an autogenerated mock type for the IOrderController type
type IOrderController struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: c
func (_m *IOrderController) CreateOrder(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewIOrderController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIOrderController creates a new instance of IOrderController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIOrderController(t mockConstructorTestingTNewIOrderController) *IOrderController {
	mock := &IOrderController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
