// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "order-service/domain/dto/orderhistory"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// IOrderHistoryRepository is an autogenerated mock type for the IOrderHistoryRepository type
type IOrderHistoryRepository struct {
	mock.Mock
}

// BulkCreate provides a mock function with given fields: _a0, _a1, _a2
func (_m *IOrderHistoryRepository) BulkCreate(_a0 context.Context, _a1 *gorm.DB, _a2 []dto.OrderHistoryRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, []dto.OrderHistoryRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0, _a1, _a2
func (_m *IOrderHistoryRepository) Create(_a0 context.Context, _a1 *gorm.DB, _a2 *dto.OrderHistoryRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *gorm.DB, *dto.OrderHistoryRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOrderHistoryRepository creates a new instance of IOrderHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrderHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrderHistoryRepository {
	mock := &IOrderHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
