// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	controllers "order-service/controllers/http/suborder"

	mock "github.com/stretchr/testify/mock"
)

// IControllerRegistry is an autogenerated mock type for the IControllerRegistry type
type IControllerRegistry struct {
	mock.Mock
}

// GetSubOrder provides a mock function with given fields:
func (_m *IControllerRegistry) GetSubOrder() controllers.ISubOrderController {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubOrder")
	}

	var r0 controllers.ISubOrderController
	if rf, ok := ret.Get(0).(func() controllers.ISubOrderController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(controllers.ISubOrderController)
		}
	}

	return r0
}

// NewIControllerRegistry creates a new instance of IControllerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIControllerRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IControllerRegistry {
	mock := &IControllerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
