// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IKafkaRouter is an autogenerated mock type for the IKafkaRouter type
type IKafkaRouter struct {
	mock.Mock
}

// Register provides a mock function with given fields:
func (_m *IKafkaRouter) Register() {
	_m.Called()
}

// NewIKafkaRouter creates a new instance of IKafkaRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIKafkaRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IKafkaRouter {
	mock := &IKafkaRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
