// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRouteRegistry is an autogenerated mock type for the IRouteRegistry type
type IRouteRegistry struct {
	mock.Mock
}

// Serve provides a mock function with given fields:
func (_m *IRouteRegistry) Serve() {
	_m.Called()
}

// NewIRouteRegistry creates a new instance of IRouteRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRouteRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRouteRegistry {
	mock := &IRouteRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
