// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISubOrderRoute is an autogenerated mock type for the ISubOrderRoute type
type ISubOrderRoute struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *ISubOrderRoute) Run() {
	_m.Called()
}

// NewISubOrderRoute creates a new instance of ISubOrderRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISubOrderRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISubOrderRoute {
	mock := &ISubOrderRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
